<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nogaru | Car rentals made simple</title>
    <link href="{{ asset('theme/assets/css/vendors.min.css') }}" rel="stylesheet"><link href="{{ asset('theme/assets/css/app.min.css') }}" rel="stylesheet">
    <style>
        :root { --navy:#10243e; --blue:#276ef1; } body{color:var(--navy)} .brand{font-size:1.5rem;letter-spacing:-.06em}.hero{color:#fff;background:linear-gradient(90deg,rgba(10,29,52,.94),rgba(10,29,52,.35)),url('{{ asset('theme/assets/images/landing-cta.jpg') }}') center/cover}.hero-copy{padding:105px 0 155px;max-width:700px}.hero h1{font-size:clamp(3rem,6vw,5rem);letter-spacing:-.06em}.search-card{margin-top:-65px;box-shadow:0 18px 45px #10243e26;border:0;border-radius:18px}.section{padding:88px 0}.kicker{color:var(--blue);font-size:.75rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.section-title{font-size:clamp(2rem,3vw,3rem);letter-spacing:-.045em}.destination{height:260px;background-size:cover;background-position:center;border:0;overflow:hidden}.destination:before{content:'';position:absolute;inset:0;background:linear-gradient(transparent,rgba(10,29,52,.9))}.destination .card-body{z-index:1}.vehicle-img{height:200px;object-fit:cover;background:#edf2f8}.testimonial,.footer{background:var(--navy);color:#fff}.feature{background:#eef4ff;color:var(--blue);border-radius:14px}.faq summary{cursor:pointer;font-weight:700;padding:1rem 0}.faq{border-bottom:1px solid #e6edf5}.price-featured{background:var(--blue);color:#fff}.company-mark{width:50px;height:50px;display:grid;place-items:center;background:#eaf1ff;color:var(--blue);border-radius:14px;font-weight:800}
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-white border-bottom sticky-top"><div class="container py-2"><a class="navbar-brand brand fw-bold" href="{{ route('home') }}"><i class="ti ti-steering-wheel text-primary"></i> Nogaru</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><i class="ti ti-menu-2"></i></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav mx-auto"><li class="nav-item"><a class="nav-link" href="#rentals">Rentals</a></li><li class="nav-item"><a class="nav-link" href="#destinations">Destinations</a></li><li class="nav-item"><a class="nav-link" href="#owners">For owners</a></li></ul>@auth<a class="btn btn-light" href="{{ route('dashboard') }}">Dashboard</a>@else<a class="btn btn-primary" href="{{ route('register') }}">Create account</a>@endauth</div></div></nav>
<main>
<section class="hero"><div class="container"><div class="hero-copy"><p class="kicker text-info"><i class="ti ti-sparkles"></i> {{ $content['hero_eyebrow'] }}</p><h1 class="fw-bold">{{ $content['hero_title'] }}<br><span class="text-info">{{ $content['hero_highlight'] }}</span></h1><p class="fs-17 text-white-50">{{ $content['hero_subtitle'] }}</p></div></div></section>
<div class="container"><form action="{{ route('marketplace.index') }}" class="card search-card" method="GET"><div class="card-body p-4"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Pick-up location</label><input class="form-control" name="location" placeholder="City or airport"></div><div class="col-md-2"><label class="form-label">Pick-up date</label><input class="form-control" type="date" name="pickup_date"></div><div class="col-md-2"><label class="form-label">Return date</label><input class="form-control" type="date" name="return_date"></div><div class="col-md-2"><label class="form-label">Vehicle type</label><select class="form-select" name="vehicle_type"><option value="">Any vehicle</option><option>Sedan</option><option>SUV</option><option>Van</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100" type="submit"><i class="ti ti-search"></i> Search</button></div></div></div></form></div>
<section class="section" id="rentals"><div class="container"><p class="kicker">Trusted local partners</p><div class="d-flex justify-content-between mb-4"><h2 class="section-title fw-bold mb-0">{{ $content['company_heading'] }}</h2><a href="{{ route('businesses.index') }}">All companies <i class="ti ti-arrow-right"></i></a></div><div class="row g-3">@forelse($businesses as $business)<div class="col-sm-6 col-lg-3"><a class="card h-100 text-decoration-none" href="{{ route('businesses.show', $business->slug) }}"><div class="card-body d-flex gap-3 align-items-center"><span class="company-mark">{{ str($business->name)->substr(0, 1) }}</span><span><strong class="d-block text-dark">{{ $business->name }}</strong><small class="text-muted">{{ $business->city ?: 'Philippines' }} · {{ $business->cars_count }} vehicles</small></span></div></a></div>@empty<p class="text-muted">Rental companies will appear here soon.</p>@endforelse</div></div></section>
<section class="section bg-light" id="destinations"><div class="container"><div class="text-center mb-5"><p class="kicker">Explore by place</p><h2 class="section-title fw-bold">{{ $content['destination_heading'] }}</h2></div><div class="row g-4">@foreach([['Manila','City escapes & business trips','gallery/1.jpg'],['Cebu','Sun, sea & island days','gallery/2.jpg'],['Baguio','Cool mountain drives','gallery/3.jpg'],['Davao','Go further, comfortably','gallery/4.jpg']] as [$place,$subtitle,$image])<div class="col-sm-6 col-lg-3"><a href="{{ route('marketplace.index',['location'=>$place]) }}" class="card destination position-relative text-white text-decoration-none" style="background-image:url('{{ asset('theme/assets/images/'.$image) }}')"><div class="card-body d-flex h-100 flex-column justify-content-end"><h3 class="h4 text-white">{{ $place }}</h3><span class="small text-white-50">{{ $subtitle }}</span></div></a></div>@endforeach</div></div></section>
<section class="section"><div class="container"><p class="kicker">Ready when you are</p><div class="d-flex justify-content-between mb-4"><h2 class="section-title fw-bold mb-0">{{ $content['vehicle_heading'] }}</h2><a href="{{ route('marketplace.index') }}">Browse all vehicles <i class="ti ti-arrow-right"></i></a></div><div class="row g-4">@forelse($cars as $car)@php($dailyRate = $car->rates->whereIn('name',['24hrs','Daily'])->min('value') ?? $car->rates->min('value'))<div class="col-md-6 col-xl-4"><x-vehicle-card :title="$car->car_model ?: $car->vehicle_type" :image="$car->images->first()?->image_path" :status="$car->status" :seats="$car->seats" :vehicle-type="$car->vehicle_type" :transmission="$car->transmission" :rental-type="$car->rental_type" :price="$dailyRate ? '₱'.number_format((float) $dailyRate, 0) : null" :price-label="$car->rates->firstWhere('name', '24hrs') ? '24hrs' : 'day'" :secondary-price="$dailyRate ? 'From ₱'.number_format((float) $dailyRate, 0).' per day' : null" :href="route('vehicles.show', $car)" /></div>@empty<p class="text-muted">Featured vehicles will appear here soon.</p>@endforelse</div></div></section>
<section class="section bg-light"><div class="container"><div class="row g-5"><div class="col-lg-5"><p class="kicker">Why Nogaru</p><h2 class="section-title fw-bold">{{ $content['why_heading'] }}</h2><p class="text-muted">We make it easy to compare trusted local companies, find the right vehicle, and get on your way.</p></div><div class="col-lg-7"><div class="row g-3">@foreach([['ti ti-building-store','Local companies, one place'],['ti ti-adjustments-horizontal','Compare with confidence'],['ti ti-headset','Support for your journey'],['ti ti-shield-check','A safer way to rent']] as [$icon,$title])<div class="col-sm-6"><div class="bg-white p-4 h-100 rounded-3"><span class="feature d-inline-block p-3"><i class="{{ $icon }}"></i></span><h3 class="h5 mt-3">{{ $title }}</h3><p class="small text-muted mb-0">Clear choices and helpful details for every trip.</p></div></div>@endforeach</div></div></div></div></section>
<section class="section"><div class="container"><div class="testimonial p-5 rounded-4"><i class="ti ti-star-filled text-warning"></i> <i class="ti ti-star-filled text-warning"></i> <i class="ti ti-star-filled text-warning"></i> <i class="ti ti-star-filled text-warning"></i> <i class="ti ti-star-filled text-warning"></i><blockquote class="fs-3 fw-semibold mt-3">“{{ $content['testimonial']['quote'] }}”</blockquote><strong>{{ $content['testimonial']['name'] }}</strong><span class="d-block text-white-50 small">{{ $content['testimonial']['role'] }}</span></div></div></section>
<section class="section bg-light" id="owners"><div class="container"><div class="text-center mb-5"><p class="kicker">For rental businesses</p><h2 class="section-title fw-bold">{{ $content['pricing_heading'] }}</h2></div><div class="row justify-content-center g-4"><div class="col-md-5"><div class="card h-100"><div class="card-body p-5"><h3>Get listed</h3><p class="text-muted">For rental teams ready to be discovered online.</p><h2>Free</h2><p>Business profile · Fleet listings · Booking enquiries</p><a class="btn btn-outline-primary w-100" href="{{ route('business.register') }}">Join Nogaru</a></div></div></div><div class="col-md-5"><div class="card price-featured h-100"><div class="card-body p-5"><h3>Run it all</h3><p class="text-white-50">For growing companies that need more control.</p><h2>Let’s talk</h2><p>Booking management · Rates & availability · Customer records</p><a class="btn btn-light text-primary w-100" href="{{ route('business.register') }}">Get started</a></div></div></div></div></div></section>
<section class="section"><div class="container"><div class="row"><div class="col-lg-4"><p class="kicker">Need to know</p><h2 class="section-title fw-bold">{{ $content['faq_heading'] }}</h2></div><div class="col-lg-8">@foreach([['How do I book a vehicle?','Search for a vehicle, review its details, then follow the booking steps with your chosen rental company.'],['Can I compare rental companies?','Yes. Browse companies and vehicles in one place, then choose the option that suits your trip.'],['What do I need to rent a car?','Requirements can vary by company. You will normally need a valid driver’s licence and booking details.'],['Can I list my rental business on Nogaru?','Absolutely. Create an account to begin setting up your business profile and fleet.']] as [$question,$answer])<details class="faq" @if($loop->first) open @endif><summary>{{ $question }}</summary><p class="text-muted">{{ $answer }}</p></details>@endforeach</div></div></div></section>
</main>
<footer class="footer py-5"><div class="container"><div class="row"><div class="col-lg-6"><h3 class="fw-bold">Nogaru</h3><p class="text-white-50">{{ $content['footer_text'] }}</p></div><div class="col-lg-6 text-lg-end"><a class="btn btn-light text-primary" href="{{ route('marketplace.index') }}">Search vehicles</a></div></div><div class="border-top border-secondary pt-3 mt-4 small text-white-50">© {{ now()->year }} Nogaru. All rights reserved.</div></div></footer>
<script src="{{ asset('theme/assets/js/vendors.min.js') }}"></script><script src="{{ asset('theme/assets/js/app.js') }}"></script>
</body></html>
