@extends('layouts.theme')

@section('title', 'Partner Fleets | Nogaru Car Rental')
@section('page-title', 'Partner Fleet Vehicles')
@section('page-actions')
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPartnerFleetModal"><i class="ti ti-plus me-1"></i> Add & request partner unit</button>
@endsection

@section('content')
    @if (session('success'))<div class="alert alert-success alert-dismissible fade show">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
    @if ($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="card mb-4"><div class="card-body"><h4 class="header-title">Approved partner fleet units</h4><p class="text-muted">Approved units can be used when your own fleet cannot fulfil a booking.</p><div class="table-responsive"><table class="table table-hover table-centered mb-0"><thead><tr><th>Business name</th><th>Unit info</th><th class="text-end">Action</th></tr></thead><tbody>@forelse ($approvedRequests as $partnerFleetRequest)<tr><td><strong>{{ $partnerFleetRequest->partnerBusiness->name }}</strong></td><td>{{ $partnerFleetRequest->car->car_model ?: $partnerFleetRequest->car->vehicle_type }} @if ($partnerFleetRequest->car->variant)<span class="text-muted">&middot; {{ $partnerFleetRequest->car->variant }}</span>@endif <small class="d-block text-muted">{{ $partnerFleetRequest->car->plate_number ?: 'No plate number' }}</small></td><td class="text-end"><span class="badge bg-success-subtle text-success me-2">Approved</span><form class="d-inline" method="POST" action="{{ route('business.partner-fleets.destroy', $partnerFleetRequest) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Remove this partner fleet unit?')">Remove</button></form></td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">No partner fleet units have been approved yet.</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="card"><div class="card-body"><h4 class="header-title">Requests awaiting your approval</h4><div class="table-responsive"><table class="table table-hover table-centered mb-0"><thead><tr><th>Requesting business</th><th>Requested unit</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse ($receivedRequests as $partnerFleetRequest)<tr><td>{{ $partnerFleetRequest->requestingBusiness->name }}</td><td>{{ $partnerFleetRequest->car->car_model ?: $partnerFleetRequest->car->vehicle_type }} <small class="text-muted">{{ $partnerFleetRequest->car->plate_number }}</small></td><td class="text-end"><form class="d-inline" method="POST" action="{{ route('business.partner-fleets.approve', $partnerFleetRequest) }}">@csrf @method('PUT')<button class="btn btn-sm btn-success">Approve</button></form> <form class="d-inline" method="POST" action="{{ route('business.partner-fleets.reject', $partnerFleetRequest) }}">@csrf @method('PUT')<button class="btn btn-sm btn-outline-danger">Decline</button></form></td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">No requests are waiting for approval.</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="modal fade" id="addPartnerFleetModal" tabindex="-1" aria-labelledby="addPartnerFleetModalLabel" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('business.partner-fleets.store') }}">@csrf<div class="modal-header"><h5 class="modal-title" id="addPartnerFleetModalLabel">Request a partner fleet unit</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="text-muted small">The partner business must approve your request before the unit is available to use.</p><div class="mb-3"><label for="partner_business_id" class="form-label">Partner business</label><select id="partner_business_id" class="form-select" name="partner_business_id" required><option value="">Select a business</option>@foreach ($partnerBusinesses as $partnerBusiness)<option value="{{ $partnerBusiness->id }}">{{ $partnerBusiness->name }}</option>@endforeach</select></div><div class="mb-0"><label for="car_id" class="form-label">Partner fleet unit</label><select id="car_id" class="form-select" name="car_id" required disabled><option value="">Select a business first</option></select></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Request unit</button></div></form></div></div></div>
@endsection

@push('scripts')
<script>
const partnerFleetUnits = @json($partnerFleetUnits);
const partnerBusinessSelect = document.getElementById('partner_business_id');
const partnerCarSelect = document.getElementById('car_id');
partnerBusinessSelect.addEventListener('change', () => { const units = partnerFleetUnits[partnerBusinessSelect.value] || []; partnerCarSelect.innerHTML = '<option value="">' + (units.length ? 'Select a fleet unit' : 'No available units') + '</option>'; units.forEach((unit) => partnerCarSelect.add(new Option(unit.label, unit.id))); partnerCarSelect.disabled = units.length === 0; });
</script>
@endpush
