@extends('layouts.theme')

@section('title', $driver->full_name.' | Drivers')
@section('page-title', 'Driver Profile')
@section('content')
    <div class="page-title-box"><div class="page-title-right"><a href="{{ route('business.drivers.index') }}" class="btn btn-outline-secondary btn-sm"><i class="ti ti-arrow-left me-1"></i>Drivers</a></div><h4 class="page-title">Driver Profile</h4></div>
    <div class="card mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-start"><div><h4 class="mb-1">{{ $driver->full_name }}</h4><p class="text-muted mb-1">Licence: {{ $driver->license_number }}</p><p class="text-muted mb-0">{{ $driver->phone ?: $driver->email ?: 'No contact details' }}</p></div><span class="badge {{ $driver->pivot->is_default ? 'bg-primary' : 'bg-secondary' }}">{{ $driver->pivot->is_default ? 'Default Driver' : 'Driver' }}</span></div></div></div>
    <div class="row g-4"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Upcoming Travels</h5></div><div class="card-body">@forelse($upcomingTravels as $booking)<div class="border-bottom pb-3 mb-3"><strong>{{ $booking->user?->clientProfile?->full_name ?: $booking->user?->name ?: 'Guest client' }}</strong><span class="badge bg-info-subtle text-info float-end">{{ str($booking->status)->headline() }}</span><div class="small text-muted mt-1">{{ $booking->car?->car_model ?: $booking->preferred_vehicle }} · {{ $booking->pickup_date?->format('M j, Y') }} {{ $booking->pickup_time }}</div><div class="small text-muted">{{ $booking->pickup_location }} → {{ $booking->return_location }}</div></div>@empty<p class="text-muted mb-0">No upcoming client travels assigned.</p>@endforelse</div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Done Travels</h5></div><div class="card-body">@forelse($completedTravels as $booking)<div class="border-bottom pb-3 mb-3"><strong>{{ $booking->user?->clientProfile?->full_name ?: $booking->user?->name ?: 'Guest client' }}</strong><span class="badge bg-success-subtle text-success float-end">Completed</span><div class="small text-muted mt-1">{{ $booking->car?->car_model ?: $booking->preferred_vehicle }} · {{ $booking->pickup_date?->format('M j, Y') }}</div><div class="small text-muted">{{ $booking->pickup_location }} → {{ $booking->return_location }}</div></div>@empty<p class="text-muted mb-0">No completed client travels assigned.</p>@endforelse</div></div></div></div>
@endsection
