@extends('layouts.theme')
@section('title', 'Edit Payment Method | Nogaru Car Rental')
@section('page-title', 'Edit Payment Method')
@section('content')
    <div class="card" style="max-width: 720px"><div class="card-body"><form method="POST" action="{{ route('business.payment-methods.update', $paymentMethod) }}" enctype="multipart/form-data">@csrf @method('PUT')
        <div class="d-flex justify-content-between align-items-center mb-3"><h4 class="header-title mb-0">Edit Payment Method</h4><a href="{{ route('business.payment-methods.index') }}" class="btn btn-outline-secondary btn-sm">Cancel</a></div>
        <div class="row g-3"><div class="col-md-6"><label class="form-label">Payment Method</label><input class="form-control" name="payment_method" value="{{ old('payment_method', $paymentMethod->payment_method) }}" required></div><div class="col-md-6"><label class="form-label">Account Type</label><input class="form-control" name="account_type" value="{{ old('account_type', $paymentMethod->account_type) }}" required></div><div class="col-md-6"><label class="form-label">Account Name</label><input class="form-control" name="account_name" value="{{ old('account_name', $paymentMethod->account_name) }}" required></div><div class="col-md-6"><label class="form-label">Account Number</label><input class="form-control" name="account_number" value="{{ old('account_number', $paymentMethod->account_number) }}" required></div><div class="col-md-6"><label class="form-label">Swift Code</label><input class="form-control" name="swift_code" value="{{ old('swift_code', $paymentMethod->swift_code) }}"></div><div class="col-md-3"><label class="form-label">Account Category</label><select class="form-select" name="account_category" required><option value="Savings" @selected(old('account_category', $paymentMethod->account_category) === 'Savings')>Savings</option><option value="Checking" @selected(old('account_category', $paymentMethod->account_category) === 'Checking')>Checking</option></select></div><div class="col-md-3"><label class="form-label">Currency</label><input class="form-control" name="currency" value="{{ old('currency', $paymentMethod->currency) }}" required></div><div class="col-12"><label class="form-label">Replace QR Code <span class="text-muted">(optional)</span></label><input class="form-control" type="file" name="qr_code" accept="image/*">@if($paymentMethod->qr_code_path)<img src="{{ asset('storage/'.$paymentMethod->qr_code_path) }}" alt="Current QR code" class="img-thumbnail mt-2" style="height: 120px; width: 120px; object-fit: contain;">@endif</div></div>
        <button class="btn btn-primary mt-4" type="submit">Save Changes</button>
    </form></div></div>
@endsection
