@extends('layouts.theme')

@section('title', 'Vehicle Inspection | Nogaru Car Rental')
@section('page-title', 'Vehicle Inspection #'.$booking->id)
@section('page-actions')<a href="{{ route('business.bookings.index') }}" class="btn btn-outline-secondary">Back to bookings</a>@endsection

@section('content')
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="card mb-3"><div class="card-body"><strong>{{ $booking->car?->car_model ?? $booking->preferred_vehicle }}</strong> · {{ $booking->user?->name }} · {{ $booking->pickup_date?->format('M d, Y') }} to {{ $booking->return_date?->format('M d, Y') }}</div></div>
    <div class="row g-3">@foreach(['before' => 'Before handover', 'after' => 'After return'] as $stage => $title)<div class="col-lg-6"><div class="card h-100"><div class="card-header"><h4 class="header-title mb-0">{{ $title }}</h4></div><div class="card-body">@php($inspection = $booking->inspections->firstWhere('stage', $stage))<form method="POST" action="{{ route('business.bookings.inspection.store', $booking) }}" enctype="multipart/form-data">@csrf<input type="hidden" name="stage" value="{{ $stage }}"><div class="row g-2 mb-3">@foreach(['Exterior clean', 'Tires checked', 'Fuel level recorded', 'Interior clean', 'Documents present'] as $item)<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="checklist[{{ $loop->index }}]" value="{{ $item }}" id="{{ $stage }}-{{ $loop->index }}" @checked(in_array($item, $inspection?->checklist ?? []))><label class="form-check-label" for="{{ $stage }}-{{ $loop->index }}">{{ $item }}</label></div></div>@endforeach</div><label class="form-label">Damage notes</label><textarea name="damage_notes" class="form-control mb-3" rows="3" placeholder="Record existing or newly found damage">{{ $inspection?->damage_notes }}</textarea><label class="form-label">Photos</label><input type="file" name="photos[]" class="form-control mb-3" accept="image/*" multiple>@if($inspection?->photo_paths)<div class="d-flex gap-2 flex-wrap mb-3">@foreach($inspection->photo_paths as $photo)<a href="{{ asset('storage/'.$photo) }}" target="_blank"><img src="{{ asset('storage/'.$photo) }}" alt="Inspection photo" width="70" height="55" class="rounded" style="object-fit:cover"></a>@endforeach</div>@endif<button class="btn btn-primary">Save {{ strtolower($title) }} inspection</button></form></div></div></div>@endforeach</div>
@endsection
